# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

changelog:
  exclude:
    labels:
      - ignore-for-release

  categories:
    - title: "💥 Breaking Changes"
      labels:
        - is:breaking

    - title: "✨ New Rules"
      labels:
        - a:feature
        - in:rules
      exclude:
        labels:
          - is:invalid
          - is:wontfix
          - is:duplicate

    - title: "🐛 Rule Changes"
      labels:
        - a:bug
        - in:rules
      exclude:
        labels:
          - is:invalid
          - is:wontfix
          - is:duplicate

    - title: "🐛 Rule Changes"
      labels:
        - a:enhancement
        - in:rules
      exclude:
        labels:
          - is:invalid
          - is:wontfix
          - is:duplicate

    - title: "⬆️ Dependency Updates"
      labels:
        - in:dependencies

    - title: "🤫 Not included"
      labels:
        - is:invalid
        - is:wontfix
        - is:duplicate

    - title: "❓ Other Changes"
      labels:
        - "*"
