name: "GH-Lint"
description: "Run ghlint on GitHub Actions files"
inputs:
  version:
    description: "The version of ghlint to use. Use 'latest' to always use the latest version, may break over time."
    default: "0.2.0"
  files:
    description: "The files to lint."
    default: |
      ${{ github.workspace }}/.github/workflows/*.yml
      ${{ github.workspace }}/action.yml
      ${{ github.workspace }}/.github/actions/action.yml
      ${{ github.workspace }}/actions/*/action.yml

runs:
  using: composite
  steps:

    - name: "Set up Java."
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin

    - name: "Download validator."
      env:
        GHLINT_VERSION: ${{ inputs.version }}
      shell: bash
      run: |
        curl --silent --show-error --location --remote-name \
            https://github.com/TWiStErRob/net.twisterrob.ghlint/releases/download/v${GHLINT_VERSION}/ghlint.jar
        chmod +x ghlint.jar

    - name: "Calculate files to check"
      id: files
      env:
        FILES: ${{ inputs.files }}
      uses: actions/github-script@v7
      with:
        script: |
          const files = process.env.FILES;
          const globber = glob.create(files, { followSymbolicLinks: false });
          const result = [];
          for await (const file of globber.globGenerator()) {
          	result.push(file);
          }
          return result.join("\n");

    - name: "Run validator."
      env:
        FILES: ${{ steps.files.outputs.result }}
      shell: bash
      run: echo "${FILES}" | xargs ./ghlint.jar
