site_name: GH-Lint documentation
repo_url: https://github.com/TWiStErRob/net.twisterrob.ghlint/

theme:
  name: material

markdown_extensions:
  - pymdownx.superfences:
  - toc:
      permalink: true
