name: "Release: Publish"

on:
  push:
    branches:
      - main

jobs:
  release:
    name: "Release"
    if: ${{ startsWith(github.event.head_commit.message, 'Release v') }}
    
    permissions:
      # read: actions/checkout
      # write: gh release create
      contents: write

    runs-on: ubuntu-latest
    timeout-minutes: 5

    defaults:
      run:
        shell: bash

    steps:

      - name: "Checkout ${{ github.ref }} branch in ${{ github.repository }} repository."
        uses: actions/checkout@v4

      - name: "Set up Java."
        uses: actions/setup-java@v4
        with:
          java-version-file: .java-version
          distribution: temurin

      - name: "Build CLI."
        run: >
          ./gradlew
          --no-daemon
          --continue
          --stacktrace
          versionFile
          fatJar
          distZip

      - name: "Create Release."
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          version=$(cat modules/ghlint/build/version.txt)
          gh release create "v${version}" \
            --title "Release v${version}" \
            --latest \
            --generate-notes \
            "modules/ghlint/build/libs/ghlint-${version}-fat.jar" \
            "modules/ghlint/build/distributions/ghlint-${version}.zip"
